openai:
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen-plus"
  temperature: 0.7
  max_tokens: 20
  timeout: 30

browser:
  headless: false
  browser_type: "firefox"  # chromium, firefox, webkit
  viewport:
    width: 1280
    height: 720
  timeout: 30000

automation:
  typing_delay: 0  # milliseconds between keystrokes
  action_delay: 1  # milliseconds between actions
  max_retries: 3

resume_parsing:
  supported_formats: ["pdf", "docx", "doc"]
  output_file: "parsed_resume.json"
  
logging:
  level: "INFO"
  file: "automation.log" 